### PR TITLE
Simplify code and readable

### PR DESCRIPTION
**Pull request by nulls-jp**
Add extension for simplify and code convention for readable code

### CODE REVIEW

**Review by agustiyann — APPROVED** [review]
All LGTM!! Thanks for the PR 👍

**Comment by agustiyann** [comment]
Hi @jejemo I want to ask, why is your profile not visible as a contributor after I merge the PR ?? I am confused :confused:

**Comment by Hazmi35** [comment]
Sorry to hijack the conversation, but it's probably because of the author's email in the GitHub account and the author's email on git config user.email (`git config --get user.email`) mismatched or not added to the author's GitHub account emails

**Comment by agustiyann** [comment]
@Hazmi35 yes after I searching for it, I think so. btw thanks for the information

**Pull request merged**
